import { 
  Produto, 
  ItemEstoque, 
  OrdemProducao, 
  MovimentacaoEstoque, 
  ApontamentoProducao, 
  ParadaMaquina, 
  Usuario 
} from '../types';

export const INITIAL_USUARIOS: Usuario[] = [
  {
    id: 'user-1',
    nome: 'Eng. Roberto Mendes',
    email: 'roberto.mendes@industria.com.br',
    perfil: 'ADMINISTRADOR',
    departamento: 'Diretoria Industrial',
    ativo: true,
  },
  {
    id: 'user-2',
    nome: 'Fernanda Carvalho',
    email: 'fernanda.carvalho@industria.com.br',
    perfil: 'PCP',
    departamento: 'Planejamento e Controle da Produção',
    ativo: true,
  },
  {
    id: 'user-3',
    nome: 'Marcos Silveira',
    email: 'marcos.silveira@industria.com.br',
    perfil: 'PRODUCAO',
    departamento: 'Chão de Fábrica / Linhas de Usinagem',
    ativo: true,
  },
  {
    id: 'user-4',
    nome: 'Cláudio Nogueira',
    email: 'claudio.almoxarifado@industria.com.br',
    perfil: 'ESTOQUE',
    departamento: 'Almoxarifado Central & Abastecimento',
    ativo: true,
  },
  {
    id: 'user-5',
    nome: 'Dra. Beatriz Fontana',
    email: 'beatriz.fontana@industria.com.br',
    perfil: 'GESTOR',
    departamento: 'Gerência de Operações e Qualidade',
    ativo: true,
  },
  {
    id: 'user-6',
    nome: 'Auditoria Externa',
    email: 'auditor@consultoria.com.br',
    perfil: 'VISUALIZACAO',
    departamento: 'Auditoria de Processos',
    ativo: true,
  },
];

export const INITIAL_ESTOQUE: ItemEstoque[] = [
  {
    id: 'mat-001',
    codigo: 'MP-ACO-1020',
    nome: 'Tarugo de Aço SAE 1020 Ø 50mm',
    categoria: 'MATERIA_PRIMA',
    unidadeMedida: 'KG',
    estoqueAtual: 420,
    estoqueMinimo: 350,
    estoqueMaximo: 2000,
    localArmazenamento: 'Galpão 01 - Racks A-02',
    custoUnitario: 18.5,
  },
  {
    id: 'mat-002',
    codigo: 'MP-ALUM-6061',
    nome: 'Barra Redonda Alumínio 6061 T6',
    categoria: 'MATERIA_PRIMA',
    unidadeMedida: 'KG',
    estoqueAtual: 85, // Crítico! Abaixo do mínimo
    estoqueMinimo: 180,
    estoqueMaximo: 800,
    localArmazenamento: 'Galpão 01 - Racks B-04',
    custoUnitario: 34.0,
  },
  {
    id: 'mat-003',
    codigo: 'COMP-ROL-6205',
    nome: 'Rolamento Blindado 6205 DDU',
    categoria: 'COMPONENTE',
    unidadeMedida: 'PC',
    estoqueAtual: 140,
    estoqueMinimo: 100,
    estoqueMaximo: 600,
    localArmazenamento: 'Almoxarifado Central - Prateleira C-12',
    custoUnitario: 24.8,
  },
  {
    id: 'mat-004',
    codigo: 'COMP-VED-OR70',
    nome: 'Anel de Vedação O-Ring Nitrílica 70 Shore',
    categoria: 'COMPONENTE',
    unidadeMedida: 'PC',
    estoqueAtual: 520,
    estoqueMinimo: 250,
    estoqueMaximo: 2500,
    localArmazenamento: 'Almoxarifado Central - Gaveteiro G-05',
    custoUnitario: 3.2,
  },
  {
    id: 'mat-005',
    codigo: 'FIX-PAR-M8X35',
    nome: 'Parafuso Allen Cabeça Cilíndrica M8x35 Cl 8.8',
    categoria: 'COMPONENTE',
    unidadeMedida: 'PC',
    estoqueAtual: 45, // Muito Crítico!
    estoqueMinimo: 400,
    estoqueMaximo: 3000,
    localArmazenamento: 'Almoxarifado Central - Gaveteiro G-14',
    custoUnitario: 1.15,
  },
  {
    id: 'mat-006',
    codigo: 'INS-TINT-EPX',
    nome: 'Tinta Epóxi Eletrostática Azul Industrial',
    categoria: 'MATERIA_PRIMA',
    unidadeMedida: 'KG',
    estoqueAtual: 210,
    estoqueMinimo: 80,
    estoqueMaximo: 500,
    localArmazenamento: 'Cabine de Pintura - Depósito Inflamáveis',
    custoUnitario: 45.0,
  },
  {
    id: 'mat-007',
    codigo: 'EMB-CX-KRAFT40',
    nome: 'Caixa de Papelão Duplo Reforçado 40x30x25cm',
    categoria: 'EMBALAGEM',
    unidadeMedida: 'UN',
    estoqueAtual: 310,
    estoqueMinimo: 150,
    estoqueMaximo: 1200,
    localArmazenamento: 'Setor de Expedição - Palete P-03',
    custoUnitario: 7.8,
  },
  {
    id: 'mat-008',
    codigo: 'COMP-SENS-IND',
    nome: 'Sensor de Proximidade Indutivo M12 NPN',
    categoria: 'COMPONENTE',
    unidadeMedida: 'PC',
    estoqueAtual: 68,
    estoqueMinimo: 30,
    estoqueMaximo: 200,
    localArmazenamento: 'Almoxarifado Central - Armário Eletrônico',
    custoUnitario: 89.0,
  },
  {
    id: 'mat-009',
    codigo: 'INS-LUB-ISO68',
    nome: 'Óleo Hidráulico Industrial ISO VG 68',
    categoria: 'MATERIA_PRIMA',
    unidadeMedida: 'L',
    estoqueAtual: 480,
    estoqueMinimo: 200,
    estoqueMaximo: 1500,
    localArmazenamento: 'Depósito de Lubrificantes - Tambores',
    custoUnitario: 16.2,
  },
];

export const INITIAL_PRODUTOS: Produto[] = [
  {
    id: 'prod-001',
    codigo: 'PRD-VC-200',
    nome: 'Válvula de Controle Hidráulico VC-200',
    descricao: 'Válvula reguladora de vazão proporcional para sistemas hidráulicos pesados (pressão máx 350 bar).',
    unidadeMedida: 'UN',
    tempoPadraoMinutos: 45,
    estoqueMinimo: 25,
    estoqueAtual: 34,
    localArmazenamento: 'Expedição - Prateleira EX-01',
    status: 'ATIVO',
    estruturaMateriais: [
      { materialId: 'mat-001', codigoMaterial: 'MP-ACO-1020', nomeMaterial: 'Tarugo de Aço SAE 1020 Ø 50mm', quantidadePorUnidade: 2.5, unidadeMedida: 'KG' },
      { materialId: 'mat-004', codigoMaterial: 'COMP-VED-OR70', nomeMaterial: 'Anel de Vedação O-Ring Nitrílica 70 Shore', quantidadePorUnidade: 4, unidadeMedida: 'PC' },
      { materialId: 'mat-005', codigoMaterial: 'FIX-PAR-M8X35', nomeMaterial: 'Parafuso Allen Cabeça Cilíndrica M8x35 Cl 8.8', quantidadePorUnidade: 6, unidadeMedida: 'PC' },
      { materialId: 'mat-007', codigoMaterial: 'EMB-CX-KRAFT40', nomeMaterial: 'Caixa de Papelão Duplo Reforçado 40x30x25cm', quantidadePorUnidade: 1, unidadeMedida: 'UN' },
    ],
  },
  {
    id: 'prod-002',
    codigo: 'PRD-EC-450',
    nome: 'Eixo Cardan Industrial Reforçado EC-450',
    descricao: 'Eixo de transmissão mecânica balanceado dinamicamente para britadores e esteiras industriais.',
    unidadeMedida: 'UN',
    tempoPadraoMinutos: 75,
    estoqueMinimo: 15,
    estoqueAtual: 12,
    localArmazenamento: 'Expedição - Prateleira EX-02',
    status: 'ATIVO',
    estruturaMateriais: [
      { materialId: 'mat-001', codigoMaterial: 'MP-ACO-1020', nomeMaterial: 'Tarugo de Aço SAE 1020 Ø 50mm', quantidadePorUnidade: 8.0, unidadeMedida: 'KG' },
      { materialId: 'mat-003', codigoMaterial: 'COMP-ROL-6205', nomeMaterial: 'Rolamento Blindado 6205 DDU', quantidadePorUnidade: 2, unidadeMedida: 'PC' },
      { materialId: 'mat-006', codigoMaterial: 'INS-TINT-EPX', nomeMaterial: 'Tinta Epóxi Eletrostática Azul Industrial', quantidadePorUnidade: 0.6, unidadeMedida: 'KG' },
      { materialId: 'mat-007', codigoMaterial: 'EMB-CX-KRAFT40', nomeMaterial: 'Caixa de Papelão Duplo Reforçado 40x30x25cm', quantidadePorUnidade: 1, unidadeMedida: 'UN' },
    ],
  },
  {
    id: 'prod-003',
    codigo: 'PRD-RP-100',
    nome: 'Redutor Planetário de Precisão RP-100',
    descricao: 'Conjunto redutor de engrenagens helicoidais com carcaça de alumínio anodizado.',
    unidadeMedida: 'UN',
    tempoPadraoMinutos: 90,
    estoqueMinimo: 20,
    estoqueAtual: 8, // Estoque abaixo do mínimo
    localArmazenamento: 'Expedição - Prateleira EX-03',
    status: 'ATIVO',
    estruturaMateriais: [
      { materialId: 'mat-002', codigoMaterial: 'MP-ALUM-6061', nomeMaterial: 'Barra Redonda Alumínio 6061 T6', quantidadePorUnidade: 3.2, unidadeMedida: 'KG' },
      { materialId: 'mat-003', codigoMaterial: 'COMP-ROL-6205', nomeMaterial: 'Rolamento Blindado 6205 DDU', quantidadePorUnidade: 3, unidadeMedida: 'PC' },
      { materialId: 'mat-005', codigoMaterial: 'FIX-PAR-M8X35', nomeMaterial: 'Parafuso Allen Cabeça Cilíndrica M8x35 Cl 8.8', quantidadePorUnidade: 8, unidadeMedida: 'PC' },
      { materialId: 'mat-009', codigoMaterial: 'INS-LUB-ISO68', nomeMaterial: 'Óleo Hidráulico Industrial ISO VG 68', quantidadePorUnidade: 0.4, unidadeMedida: 'L' },
      { materialId: 'mat-007', codigoMaterial: 'EMB-CX-KRAFT40', nomeMaterial: 'Caixa de Papelão Duplo Reforçado 40x30x25cm', quantidadePorUnidade: 1, unidadeMedida: 'UN' },
    ],
  },
  {
    id: 'prod-004',
    codigo: 'PRD-AP-080',
    nome: 'Atuador Pneumático Linear AP-80',
    descricao: 'Cilindro pneumático de dupla ação em perfil de alumínio com amortecimento pneumático ajustável.',
    unidadeMedida: 'UN',
    tempoPadraoMinutos: 35,
    estoqueMinimo: 30,
    estoqueAtual: 42,
    localArmazenamento: 'Expedição - Prateleira EX-04',
    status: 'ATIVO',
    estruturaMateriais: [
      { materialId: 'mat-002', codigoMaterial: 'MP-ALUM-6061', nomeMaterial: 'Barra Redonda Alumínio 6061 T6', quantidadePorUnidade: 1.8, unidadeMedida: 'KG' },
      { materialId: 'mat-004', codigoMaterial: 'COMP-VED-OR70', nomeMaterial: 'Anel de Vedação O-Ring Nitrílica 70 Shore', quantidadePorUnidade: 3, unidadeMedida: 'PC' },
      { materialId: 'mat-008', codigoMaterial: 'COMP-SENS-IND', nomeMaterial: 'Sensor de Proximidade Indutivo M12 NPN', quantidadePorUnidade: 2, unidadeMedida: 'PC' },
      { materialId: 'mat-007', codigoMaterial: 'EMB-CX-KRAFT40', nomeMaterial: 'Caixa de Papelão Duplo Reforçado 40x30x25cm', quantidadePorUnidade: 1, unidadeMedida: 'UN' },
    ],
  },
  {
    id: 'prod-005',
    codigo: 'PRD-FP-030',
    nome: 'Flange Cega de Alta Pressão FP-30',
    descricao: 'Flange forjada em aço carbono para tubulações de vapor e hidrocarbonetos.',
    unidadeMedida: 'UN',
    tempoPadraoMinutos: 25,
    estoqueMinimo: 50,
    estoqueAtual: 75,
    localArmazenamento: 'Expedição - Prateleira EX-05',
    status: 'ATIVO',
    estruturaMateriais: [
      { materialId: 'mat-001', codigoMaterial: 'MP-ACO-1020', nomeMaterial: 'Tarugo de Aço SAE 1020 Ø 50mm', quantidadePorUnidade: 4.2, unidadeMedida: 'KG' },
      { materialId: 'mat-006', codigoMaterial: 'INS-TINT-EPX', nomeMaterial: 'Tinta Epóxi Eletrostática Azul Industrial', quantidadePorUnidade: 0.2, unidadeMedida: 'KG' },
    ],
  },
];

// Data base do sistema: 2026-10-06
export const INITIAL_ORDENS: OrdemProducao[] = [
  {
    id: 'op-001',
    numeroOP: 'OP-2026-081',
    produtoId: 'prod-001',
    produtoCodigo: 'PRD-VC-200',
    produtoNome: 'Válvula de Controle Hidráulico VC-200',
    quantidadePlanejada: 60,
    quantidadeProduzida: 42,
    quantidadeRejeitada: 2,
    dataInicio: '2026-10-06',
    dataPrevisaoTermino: '2026-10-06',
    setorResponsavel: 'Linha de Montagem 01',
    maquina: 'Bancada Montagem M-01',
    prioridade: 'ALTA',
    status: 'EM_PRODUCAO',
    abastecido: true,
    observacoes: 'Ordem prioritária para faturamento de lote exportação.',
  },
  {
    id: 'op-002',
    numeroOP: 'OP-2026-082',
    produtoId: 'prod-002',
    produtoCodigo: 'PRD-EC-450',
    produtoNome: 'Eixo Cardan Industrial Reforçado EC-450',
    quantidadePlanejada: 30,
    quantidadeProduzida: 18,
    quantidadeRejeitada: 1,
    dataInicio: '2026-10-05',
    dataPrevisaoTermino: '2026-10-06',
    setorResponsavel: 'Usinagem Pesada',
    maquina: 'Torno CNC Mazak 02',
    prioridade: 'URGENTE',
    status: 'EM_PRODUCAO',
    abastecido: true,
    observacoes: 'Tolerância dimensional H7 no diâmetro do mancal.',
  },
  {
    id: 'op-003',
    numeroOP: 'OP-2026-083',
    produtoId: 'prod-003',
    produtoCodigo: 'PRD-RP-100',
    produtoNome: 'Redutor Planetário de Precisão RP-100',
    quantidadePlanejada: 25,
    quantidadeProduzida: 5,
    quantidadeRejeitada: 0,
    dataInicio: '2026-10-04',
    dataPrevisaoTermino: '2026-10-05', // Atrasada!
    setorResponsavel: 'Centro de Usinagem',
    maquina: 'Centro Usinagem Haas VF-3',
    prioridade: 'URGENTE',
    status: 'PAUSADA',
    abastecido: false,
    observacoes: 'Parada por falta de parafusos Allen M8 e barras de alumínio.',
  },
  {
    id: 'op-004',
    numeroOP: 'OP-2026-084',
    produtoId: 'prod-004',
    produtoCodigo: 'PRD-AP-080',
    produtoNome: 'Atuador Pneumático Linear AP-80',
    quantidadePlanejada: 50,
    quantidadeProduzida: 0,
    quantidadeRejeitada: 0,
    dataInicio: '2026-10-06',
    dataPrevisaoTermino: '2026-10-07',
    setorResponsavel: 'Linha de Montagem 02',
    maquina: 'Bancada Pneumática BP-02',
    prioridade: 'MEDIA',
    status: 'LIBERADA',
    abastecido: false,
    observacoes: 'Aguardando requisição e kit de materiais do almoxarifado.',
  },
  {
    id: 'op-005',
    numeroOP: 'OP-2026-085',
    produtoId: 'prod-005',
    produtoCodigo: 'PRD-FP-030',
    produtoNome: 'Flange Cega de Alta Pressão FP-30',
    quantidadePlanejada: 100,
    quantidadeProduzida: 0,
    quantidadeRejeitada: 0,
    dataInicio: '2026-10-07',
    dataPrevisaoTermino: '2026-10-08',
    setorResponsavel: 'Estamparia & Forja',
    maquina: 'Prensa Hidráulica 200T',
    prioridade: 'BAIXA',
    status: 'PLANEJADA',
    abastecido: false,
    observacoes: 'Lote preventivo para recomposição de estoque de segurança.',
  },
  {
    id: 'op-006',
    numeroOP: 'OP-2026-080',
    produtoId: 'prod-001',
    produtoCodigo: 'PRD-VC-200',
    produtoNome: 'Válvula de Controle Hidráulico VC-200',
    quantidadePlanejada: 40,
    quantidadeProduzida: 40,
    quantidadeRejeitada: 1,
    dataInicio: '2026-10-04',
    dataPrevisaoTermino: '2026-10-05',
    dataConclusao: '2026-10-05',
    setorResponsavel: 'Linha de Montagem 01',
    maquina: 'Bancada Montagem M-01',
    prioridade: 'MEDIA',
    status: 'CONCLUIDA',
    abastecido: true,
    observacoes: 'Concluído com 100% dos testes de estanqueidade aprovados.',
  },
  {
    id: 'op-007',
    numeroOP: 'OP-2026-079',
    produtoId: 'prod-005',
    produtoCodigo: 'PRD-FP-030',
    produtoNome: 'Flange Cega de Alta Pressão FP-30',
    quantidadePlanejada: 80,
    quantidadeProduzida: 80,
    quantidadeRejeitada: 3,
    dataInicio: '2026-10-03',
    dataPrevisaoTermino: '2026-10-04',
    dataConclusao: '2026-10-04',
    setorResponsavel: 'Estamparia & Forja',
    maquina: 'Prensa Hidráulica 200T',
    prioridade: 'BAIXA',
    status: 'CONCLUIDA',
    abastecido: true,
  },
];

export const INITIAL_MOVIMENTACOES: MovimentacaoEstoque[] = [
  {
    id: 'mov-001',
    dataHora: '2026-10-06 08:30',
    materialId: 'mat-001',
    materialCodigo: 'MP-ACO-1020',
    materialNome: 'Tarugo de Aço SAE 1020 Ø 50mm',
    tipo: 'TRANSFERENCIA_LINHA',
    quantidade: 150,
    origem: 'Galpão 01 - Racks A-02',
    destino: 'Linha de Montagem 01',
    responsavel: 'Cláudio Nogueira',
    opRelacionada: 'OP-2026-081',
    motivo: 'Abastecimento para OP-2026-081',
  },
  {
    id: 'mov-002',
    dataHora: '2026-10-06 09:15',
    materialId: 'mat-004',
    materialCodigo: 'COMP-VED-OR70',
    materialNome: 'Anel de Vedação O-Ring Nitrílica 70 Shore',
    tipo: 'TRANSFERENCIA_LINHA',
    quantidade: 240,
    origem: 'Almoxarifado Central - Gaveteiro G-05',
    destino: 'Linha de Montagem 01',
    responsavel: 'Cláudio Nogueira',
    opRelacionada: 'OP-2026-081',
    motivo: 'Abastecimento para OP-2026-081',
  },
  {
    id: 'mov-003',
    dataHora: '2026-10-05 14:00',
    materialId: 'mat-006',
    materialCodigo: 'INS-TINT-EPX',
    materialNome: 'Tinta Epóxi Eletrostática Azul Industrial',
    tipo: 'ENTRADA',
    quantidade: 100,
    origem: 'Fornecedor QuimiCor Ltda - NF 44921',
    destino: 'Cabine de Pintura - Depósito Inflamáveis',
    responsavel: 'Fernanda Carvalho',
    motivo: 'Recebimento de compra regular',
  },
  {
    id: 'mov-004',
    dataHora: '2026-10-05 16:45',
    materialId: 'mat-005',
    materialCodigo: 'FIX-PAR-M8X35',
    materialNome: 'Parafuso Allen Cabeça Cilíndrica M8x35 Cl 8.8',
    tipo: 'SAIDA_PRODUCAO',
    quantidade: 200,
    origem: 'Almoxarifado Central - Gaveteiro G-14',
    destino: 'Centro de Usinagem',
    responsavel: 'Marcos Silveira',
    opRelacionada: 'OP-2026-083',
    motivo: 'Consumo parcial montagem redutores',
  },
  {
    id: 'mov-005',
    dataHora: '2026-10-04 11:20',
    materialId: 'mat-002',
    materialCodigo: 'MP-ALUM-6061',
    materialNome: 'Barra Redonda Alumínio 6061 T6',
    tipo: 'AJUSTE',
    quantidade: -15,
    origem: 'Galpão 01 - Racks B-04',
    destino: 'Inventário Físico',
    responsavel: 'Cláudio Nogueira',
    motivo: 'Ajuste após inventário rotativo semanal',
  },
];

export const INITIAL_APONTAMENTOS: ApontamentoProducao[] = [
  {
    id: 'ap-001',
    opId: 'op-001',
    numeroOP: 'OP-2026-081',
    produtoCodigo: 'PRD-VC-200',
    produtoNome: 'Válvula de Controle Hidráulico VC-200',
    operador: 'Carlos Silva',
    maquina: 'Bancada Montagem M-01',
    setor: 'Linha de Montagem 01',
    data: '2026-10-06',
    horarioInicio: '08:00',
    horarioTermino: '11:30',
    duracaoMinutos: 210,
    quantidadeProduzida: 24,
    quantidadeAprovada: 23,
    quantidadeRejeitada: 1,
    motivoRejeicao: 'Falha de vedação no teste hidrostático',
    paradasMinutos: 15,
    eficienciaPercentual: 95.8,
    produtividadePecasHora: 7.38,
    cumprimentoMetaPercentual: 96.0,
    refugoPercentual: 4.17,
  },
  {
    id: 'ap-002',
    opId: 'op-001',
    numeroOP: 'OP-2026-081',
    produtoCodigo: 'PRD-VC-200',
    produtoNome: 'Válvula de Controle Hidráulico VC-200',
    operador: 'Juliana Costa',
    maquina: 'Bancada Montagem M-01',
    setor: 'Linha de Montagem 01',
    data: '2026-10-06',
    horarioInicio: '12:30',
    horarioTermino: '15:30',
    duracaoMinutos: 180,
    quantidadeProduzida: 18,
    quantidadeAprovada: 17,
    quantidadeRejeitada: 1,
    motivoRejeicao: 'Torque do parafuso Allen excedido',
    paradasMinutos: 10,
    eficienciaPercentual: 94.4,
    produtividadePecasHora: 6.35,
    cumprimentoMetaPercentual: 94.7,
    refugoPercentual: 5.56,
  },
  {
    id: 'ap-003',
    opId: 'op-002',
    numeroOP: 'OP-2026-082',
    produtoCodigo: 'PRD-EC-450',
    produtoNome: 'Eixo Cardan Industrial Reforçado EC-450',
    operador: 'Rodrigo Antunes',
    maquina: 'Torno CNC Mazak 02',
    setor: 'Usinagem Pesada',
    data: '2026-10-06',
    horarioInicio: '07:30',
    horarioTermino: '12:00',
    duracaoMinutos: 270,
    quantidadeProduzida: 12,
    quantidadeAprovada: 11,
    quantidadeRejeitada: 1,
    motivoRejeicao: 'Desvio dimensional no canal de chaveta',
    paradasMinutos: 30,
    eficienciaPercentual: 91.7,
    produtividadePecasHora: 3.0,
    cumprimentoMetaPercentual: 92.0,
    refugoPercentual: 8.33,
  },
  {
    id: 'ap-004',
    opId: 'op-006',
    numeroOP: 'OP-2026-080',
    produtoCodigo: 'PRD-VC-200',
    produtoNome: 'Válvula de Controle Hidráulico VC-200',
    operador: 'Carlos Silva',
    maquina: 'Bancada Montagem M-01',
    setor: 'Linha de Montagem 01',
    data: '2026-10-05',
    horarioInicio: '08:00',
    horarioTermino: '16:00',
    duracaoMinutos: 480,
    quantidadeProduzida: 40,
    quantidadeAprovada: 39,
    quantidadeRejeitada: 1,
    motivoRejeicao: 'Vazamento leve na tampa traseira',
    paradasMinutos: 45,
    eficienciaPercentual: 97.5,
    produtividadePecasHora: 5.52,
    cumprimentoMetaPercentual: 100.0,
    refugoPercentual: 2.5,
  },
];

export const INITIAL_PARADAS: ParadaMaquina[] = [
  {
    id: 'par-001',
    maquina: 'Centro Usinagem Haas VF-3',
    setor: 'Centro de Usinagem',
    data: '2026-10-06',
    horarioInicio: '09:10',
    horarioTermino: undefined,
    duracaoMinutos: 185,
    motivo: 'FALTA_MATERIAL',
    descricaoMotivo: 'Falta de barras de alumínio 6061 e parafusos M8 para OP-2026-083',
    responsavel: 'Marcos Silveira',
    opRelacionada: 'OP-2026-083',
    observacao: 'Almoxarifado em processo de cotação emergencial.',
    emAndamento: true,
  },
  {
    id: 'par-002',
    maquina: 'Torno CNC Mazak 02',
    setor: 'Usinagem Pesada',
    data: '2026-10-06',
    horarioInicio: '10:20',
    horarioTermino: '10:50',
    duracaoMinutos: 30,
    motivo: 'SETUP',
    descricaoMotivo: 'Troca de pastilhas de corte de metal duro e recalibração de zero peça',
    responsavel: 'Rodrigo Antunes',
    opRelacionada: 'OP-2026-082',
    observacao: 'Setup concluído conforme instrução de trabalho IT-12.',
    emAndamento: false,
  },
  {
    id: 'par-003',
    maquina: 'Prensa Hidráulica 200T',
    setor: 'Estamparia & Forja',
    data: '2026-10-05',
    horarioInicio: '14:00',
    horarioTermino: '15:20',
    duracaoMinutos: 80,
    motivo: 'MANUTENCAO',
    descricaoMotivo: 'Vazamento em conexão da mangueira do circuito hidráulico principal',
    responsavel: 'Equipe de Manutenção Mecânica',
    observacao: 'Substituída guarnição e reapertado niple flangeado.',
    emAndamento: false,
  },
  {
    id: 'par-004',
    maquina: 'Bancada Montagem M-01',
    setor: 'Linha de Montagem 01',
    data: '2026-10-06',
    horarioInicio: '11:15',
    horarioTermino: '11:30',
    duracaoMinutos: 15,
    motivo: 'QUALIDADE',
    descricaoMotivo: 'Inspeção amostral e ajuste no torquímetro eletrônico',
    responsavel: 'Juliana Costa',
    opRelacionada: 'OP-2026-081',
    observacao: 'Calibração confirmada pelo inspetor da qualidade.',
    emAndamento: false,
  },
  {
    id: 'par-005',
    maquina: 'Cabine de Pintura Eletrostática',
    setor: 'Pintura',
    data: '2026-10-04',
    horarioInicio: '13:00',
    horarioTermino: '14:10',
    duracaoMinutos: 70,
    motivo: 'PROBLEMA_MAQUINA',
    descricaoMotivo: 'Falha no exaustor secundário de pó de tinta',
    responsavel: 'Manutenção Elétrica',
    observacao: 'Reset do disjuntor térmico do motor exaustor.',
    emAndamento: false,
  },
];
